rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  trailing-spaces: enable
  empty-lines:
    max: 2
  document-start: disable
  document-end: disable
  comments:
    min-spaces-from-content: 1