services:
  db:
    ports:
      - "3307:3306"

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./.env 
    entrypoint: ["./wait-for-db.sh", "db", "sh", "-c", "node utils/hashLegacyPasswords.js && npx nodemon index.js"]

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    ports:
      - "3000:8080"