version: '3.8'

services:
  db:
    build: ./DB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./Backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  admin-frontend:
    build: ./Admin
    restart: unless-stopped
    ports:
      - "8080:80"

  user-frontend:
    build: ./User
    restart: unless-stopped
    ports:
      - "8081:80"

volumes:
  db_data:
