name: Lint Code

on:
  push:
    branches: [ main, dev, frontend-fix, authorization, linting ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-backend:
    name: Lint Backend (Node.js)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Backend/package-lock.json

      - name: Install backend dependencies
        working-directory: Backend
        run: npm ci

      - name: Run ESLint on backend
        working-directory: Backend
        run: npx eslint . --ext .js --max-warnings 0
        continue-on-error: false

  lint-frontend:
    name: Lint Frontend (React/TypeScript)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: Frontend
        run: npm ci

      - name: Run ESLint on frontend
        working-directory: Frontend
        run: npx eslint . --ext .ts,.tsx --max-warnings 0
        continue-on-error: false

      - name: Run TypeScript check
        working-directory: Frontend
        run: npx tsc --noEmit
        continue-on-error: false

  lint-docker:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint (Dockerfile linter)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Backend/Dockerfile
          failure-threshold: error

      - name: Run Hadolint on Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Frontend/Dockerfile
          failure-threshold: error

      - name: Run Hadolint on DB Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: DB/Dockerfile
          failure-threshold: error

  lint-yaml:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: |
            .github/workflows/
            docker-compose.yml
            docker-compose.override.yml
          config_file: .yamllint.yml
          strict: true
